version: '3'
services:
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - mern-network
  api:
    build: ./api
    container_name: api_c
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - mern-network
networks:
  mern-network:
    driver: bridge